[package]
name = "taipo"
version = "0.1.0"
authors = ["Rob Parrett <robparrett@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [
  "bevy/bevy_gltf",
  "bevy/bevy_winit",
  "bevy/render",
  "bevy/png",
]

[dependencies]
#bevy = { version = "0.4", default-features = false}
bevy = { git = "https://github.com/bevyengine/bevy/", rev="6531fcdfd27b3fbae050643116754916ca3f3b3d", default-features=false }
rand = { version = "0.7", features = ["wasm-bindgen"] }
bevy_webgl2 = {version="0.4.0"}
#bevy_tiled_prototype = { git = "https://github.com/rparrett/bevy_tiled", rev="ed4e64c38d0c00722abdfc0eceb9b043de4f0031", default-features=false, features=["web"] }
bevy_tiled_prototype = { path = "../bevy_tiled", default-features=false, features=["web"] }
nom = "6.0"
anyhow = "1.0"

[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy/", rev="6531fcdfd27b3fbae050643116754916ca3f3b3d", default-features=false }
