[package]
name = "taipo"
version = "0.1.0"
authors = ["Rob Parrett <robparrett@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [
  "bevy/bevy_gltf",
  "bevy/bevy_winit",
  "bevy/render",
  "bevy/png",
]

[dependencies]
#bevy = { version = "0.4", default-features = false}
#bevy = { path = "../bevy-fork", default-features=false }
#bevy = { git = "https://github.com/bevyengine/bevy/", rev="c69aa98a60e378a1b54d24bf26eefe49dcb372bf", default-features=false }
bevy = { git = "https://github.com/mockersf/bevy/", branch = "biggest-resource", default-features = false }
rand = { version = "0.8" }
bevy_webgl2 = {version="0.4.0"}
bevy_tiled_prototype = { git = "https://github.com/rparrett/bevy_tiled", rev="bb02f6d548089e03a847654f57e1c48067aeab68", default-features=false, features=["web"] }
#bevy_tiled_prototype = { path = "../bevy_tiled", default-features=false, features=["web"] }
nom = "6.0"
anyhow = "1.0"
ron = "0.6.2"
serde = {version = "1", features = ["derive"]}

[patch.crates-io]
#bevy = { git = "https://github.com/bevyengine/bevy/", rev="c69aa98a60e378a1b54d24bf26eefe49dcb372bf", default-features=false }
#bevy = { path = "../bevy-fork", default-features=false }
bevy = { git = "https://github.com/mockersf/bevy/", branch = "biggest-resource", default-features = false }
