[package]
name = "taipo"
version = "0.1.0"
authors = ["Rob Parrett <robparrett@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [
  "bevy/bevy_gltf",
  "bevy/bevy_winit",
  "bevy/render",
  "bevy/png",
]

[dependencies]
#bevy = { version = "0.4", default-features = false}
#bevy = { path = "../bevy-fork", default-features=false }
#bevy = { git = "https://github.com/bevyengine/bevy/", rev="1ca8ce4a799af8dab2d926366de9ac3c8d30939c", default-features=false }
bevy = { git = "https://github.com/rparrett/bevy/", rev="0791208fd06cd3b999c7dee89cabdbc3dc45d7a8", default-features=false }
#bevy_webgl2 = { version = "0.4.0" }
#bevy_webgl2 = { path = "../bevy_webgl2" }
bevy_webgl2 = { git = "https://github.com/rparrett/bevy_webgl2", rev="2af971a82f48b3da6f1083b539290248f90049db" }

bevy_tiled_prototype = { git = "https://github.com/rparrett/bevy_tiled", rev="9bb92f197ed18a19514de5cb5a7990dfadf57228", default-features=false, features=["web"] }
#bevy_tiled_prototype = { path = "../bevy_tiled", default-features=false, features=["web"] }
bevy_asset_ron = {  git = "https://github.com/rparrett/bevy_asset_ron", rev="ffb9688fc053570c1b76ad7f2dbe706a3fc36797" }
rand = { version = "0.8" }
getrandom = { version = "0.1", features = ["wasm-bindgen"] }
serde = {version = "1", features = ["derive"]}
nom = "6.0"
anyhow = "1.0"
ron = "0.6.4"

[patch.crates-io]
#bevy = { git = "https://github.com/bevyengine/bevy/", rev="1ca8ce4a799af8dab2d926366de9ac3c8d30939c", default-features=false }
bevy = { git = "https://github.com/rparrett/bevy/", rev="0791208fd06cd3b999c7dee89cabdbc3dc45d7a8", default-features=false }
#bevy = { path = "../bevy-fork", default-features=false }

[patch.'https://github.com/bevyengine/bevy']
bevy = { git = "https://github.com/rparrett/bevy/", rev="0791208fd06cd3b999c7dee89cabdbc3dc45d7a8", default-features=false }
