[package]
name = "taipo"
version = "0.1.0"
authors = ["Rob Parrett <robparrett@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.4", default-features = false }
#bevy = { git = "https://github.com/bevyengine/bevy/", rev="6531fcdfd27b3fbae050643116754916ca3f3b3d", default-features=false }
rand = { version = "0.7", features = ["wasm-bindgen"] }
bevy_webgl2 = {version="0.4.0"}
nom = "6.0"
anyhow = "1.0"
